name: trades
description: A trading app to help traders find and analyze stock market
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  shared_preferences: ^2.5.3
  hugeicons: ^0.0.11
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: false
  
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/videos/

